baseURL: http://blog.steven-burt.dev
languageCode: en-us
title: Everyday Theory

theme: hugo-clarity

DefaultContentLanguage: "en"
sectionPagesMenu: "main"
Paginate: 12
googleAnalytics: ""
enableRobotsTXT: true

author: "Steven Burt"

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
